import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's repo.
*/`;

const prod = process.argv[2] === "production";

esbuild
  .build({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    // Obsidian 运行时已内置 CodeMirror 6，@codemirror/* 必须 external：
    // 既避免 main.js 臃肿（否则 +400kb），又保证与 Obsidian 共用同一份 CM 实例，
    // 注册的编辑器扩展才能被 Obsidian 内部的 CM 正确识别（版本不一致会导致扩展失效）。
    external: [
      "obsidian",
      "electron",
      "@codemirror/state",
      "@codemirror/view",
      ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
  })
  .then(() => {
    // Obsidian 读取插件根目录的 styles.css，构建时从 src 复制
    copyFileSync("src/styles.css", "styles.css");
  })
  .catch(() => process.exit(1));
